#!/usr/bin/env bash

# Если это мердж коммит, то ничего подставлять не надо
if [[ $(cat "$1" | grep -c 'Merge') -ge 1 ]]; then
  exit 0
fi

FORMAT='[#__value__]'

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME=${BRANCH_NAME##*/}
BRANCH_NAME=${BRANCH_NAME%%-*}

BRANCH_NAME_IS_DIGIT=$(echo "${BRANCH_NAME}" | grep -cE '^[0-9]+$')

if [[ ${BRANCH_NAME_IS_DIGIT} -eq 0 ]]; then
  exit 0
fi

TASK_NAME=$(echo "${FORMAT}" | sed "s/__value__/${BRANCH_NAME}/g")
BRANCH_IN_COMMIT=$(fgrep -c "${TASK_NAME}" $1)

if [ -n "${TASK_NAME}" ] && ! [[ ${BRANCH_IN_COMMIT} -ge 1 ]]; then
  echo "${TASK_NAME} $(cat $1)" > $1
fi
