#!/usr/bin/env bash

# Nothing to substitute if it's a merge commit
if [[ $(grep -cF 'Merge' "${1}") -ge 1 ]]; then
  exit 0
fi

if [[ -f "${HOME}/.config/prepare.config" ]];
then
  . "${HOME}/.config/prepare.config"
fi

if [[ -z "${GIT_PREPARE_COMMIT_OUT_FORMAT}" ]];
then
  GIT_PREPARE_COMMIT_OUT_FORMAT='[#__value__]'
fi

if [[ -z "${GIT_PREPARE_COMMIT_REGEXP_FOR_SEARCH}" ]];
then
  GIT_PREPARE_COMMIT_REGEXP_FOR_SEARCH='\d+'
fi

if [[ -z "${GIT_PREPARE_COMMIT_REGEXP_BRANCH_TEMPLATE}" ]];
then
  GIT_PREPARE_COMMIT_REGEXP_BRANCH_TEMPLATE='issue-\d+'
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME=$(echo "${BRANCH_NAME}" | grep -owE "${GIT_PREPARE_COMMIT_REGEXP_BRANCH_TEMPLATE}")
BRANCH_NAME=$(echo "${BRANCH_NAME}" | grep -owE "${GIT_PREPARE_COMMIT_REGEXP_FOR_SEARCH}")

TASK_NAME="${GIT_PREPARE_COMMIT_OUT_FORMAT//__value__/${BRANCH_NAME}}"
BRANCH_IN_COMMIT=$(grep -cF "${TASK_NAME}" "${1}")

if [ -n "${TASK_NAME}" ] && ! [[ ${BRANCH_IN_COMMIT} -ge 1 ]]; then
  echo "${TASK_NAME} $(cat "${1}")" > "${1}"
fi
